package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var initYamlCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a starter devdebug.yaml in the current directory",
	Run: func(cmd *cobra.Command, args []string) {

		const filename = "devdebug.yaml"

		if _, err := os.Stat(filename); err == nil {
			fmt.Println("devdebug.yaml already exists -- not overwriting.")
			fmt.Println("Delete it manually and re-run if you want a fresh template.")
			os.Exit(0)
		}

		lines := []string{
			"# devdebug.yaml -- custom error pattern config",
			"# Generated by: devdebug init",
			"",
			"patterns:",
			"  - name: \"Socket Error\"",
			"    regex: \"(?i)setsockopt.*failed\"",
			"",
			"  - name: \"Protocol Error\"",
			"    keyword: \"proterr\"",
			"",
			"  - name: \"Warning Event\"",
			"    keyword: \"warning\"",
			"",
			"  - name: \"EDC Error Code\"",
			"    regex: \"EDC[0-9]+[A-Z]\"",
			"",
			"  - name: \"Auth Failure\"",
			"    keyword: \"unauthorized\"",
			"",
			"  - name: \"5xx HTTP Error\"",
			"    regex: \"HTTP [5][0-9]{2}\"",
			"",
			"  - name: \"Retry Exhausted\"",
			"    regex: \"(?i)failed after [0-9]+ retr\"",
			"",
			"  - name: \"DB Down\"",
			"    keyword: \"database unreachable\"",
			"",
		}

		content := ""
		for _, l := range lines {
			content += l + "\n"
		}

		if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
			fmt.Fprintln(os.Stderr, "ERROR: Failed to create devdebug.yaml:", err)
			os.Exit(2)
		}

		fmt.Println("SUCCESS: devdebug.yaml created!")
		fmt.Println()
		fmt.Println("Edit it to add your own patterns, then run:")
		fmt.Println("  devdebug analyze <your-log-file>")
	},
}

// hey

func init() {
	rootCmd.AddCommand(initYamlCmd)
}
